// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions getOptions({
    required String projectId,
    String? apiKey,
    String? appId,
  }) {
    return FirebaseOptions(
      apiKey: apiKey ?? 'AIzaSyPlaceholderKey',
      appId: appId ?? '1:placeholder:ios:placeholder',
      messagingSenderId: 'placeholder',
      projectId: projectId,
      storageBucket: '$projectId.firebasestorage.app',
    );
  }

  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'DefaultFirebaseOptions.currentPlatform has been deprecated. '
      'Please use DefaultFirebaseOptions.getOptions with dynamic user settings.',
    );
  }
}
